### ISSUE TITLE
Observasi/ pengumpulan data

### ISSUE THREAD

**Issue by vianoviaccs** [vianoviaccs/Cake-Miracle#1]
Dear Tia,

tolong dilakukan pendataan untuk lebih lengkapnya dalam pendataan produk dan data-data yang sekiranya bisa kita gunakan untuk project program.
dapat dicek mengenai produk2 dalam website Cake Miracle di http://cakemiracle.com/

**Comment by narulitatia** [comment]
Baik via .. Nanti saya cek..

**Comment by vianoviaccs** [comment]
produkny dibuat kolom aja tia, dbuat tabel list tolong juga cari refernsi lainnya jadi kira2 field apa aja yg dibutuhin , thanks a lot..

**Comment by narulitatia** [comment]
https://docs.google.com/presentation/d/1SB8bNw7jAxl6-nGBYxcERli5RzBKYdx2fFLy3nQT97k/edit#slide=id.g129f1c9625_2_83

Itu link nyaa yaak vi :)

**Comment by narulitatia** [comment]
Mohon di cek yaak vi . thanks :)

**Comment by vianoviaccs** [comment]
wait tomorow yah, thanks a lot.... @narulitatia

**Comment by vianoviaccs** [comment]
dear @narulitatia 

i've been checked, tolong dibuat list ke dalam bentuk tabel ya, terima kasih..
terserah dalam format word atau excell, many thanks .. :) :+1: 
nanti upload sperti biasa ters send link.
im gonna closed this issues now, thanks.

**Comment by narulitatia** [comment]
Ini list apa vi? Data nya sama seperti yg sebelumnya kah? Tapi di buat di excell atau data yang seperti apa yg di buat di tabel?

**Comment by vianoviaccs** [comment]
baca instruksinya baik2 yul, data yg lu buat itu kan macam presentasi tlong d buat versi listnya,,
pindah ke issues selanjutnya yaa.. next .. thanks

**Comment by narulitatia** [comment]
Mungkin efek sudah malam n efek lapar jadi agak ngebleng.

Baik via Novia via :)

**Comment by vianoviaccs** [comment]
@narulitatia wkwkk samaaa, nama berbi gausah diulang2 gitu, share link jgn lupa. thanks for quick responn :dancers:
