### ISSUE TITLE
Please look at the sample page here

### ISSUE THREAD

**Issue by andrysunandarbl** [vianoviaccs/Cake-Miracle#10]
[http://www.edureka.co/blog/design-pattern-exposed-factory-pattern/](http://www.edureka.co/blog/design-pattern-exposed-factory-pattern/) @lailyfitria @vianoviaccs @kuratuayuni @sapatati @narulitatia

**Comment by vianoviaccs** [comment]
Dear Pak @andrysunandarbl 

Yes Sir, we'll try later ..

Thanks a lot for your support.

Regards,

Via - Leader Team 2

cc: @kuratuayuni @lailyfitria @narulitatia @sapatati

**Comment by vianoviaccs** [comment]
@andrysunandarbl i'v done seen it, thank you Sir.
