### ISSUE TITLE
Add minimum issues for 1 member 1 issue per week, more issue more point guys...

### ISSUE THREAD

**Issue by andrysunandarbl** [vianoviaccs/Cake-Miracle#11]
@lailyfitria @vianoviaccs @kuratuayuni @sapatati @narulitatia

**Comment by vianoviaccs** [comment]
Dear Pak @andrysunandarbl 

Insya Allah sabtu ini akan kami selesaikan pak, terimakasih atas support Bapak.

Mohon maaf belom bisa merespon lebih cepat dikarenakan pekerjaan dan kuliah kami. 

Salam,

Via - Leader Team 2

cc: @kuratuayuni @lailyfitria @narulitatia @sapatati
