### ISSUE TITLE
perancangan ulang konsep program

### ISSUE THREAD

**Issue by vianoviaccs** [vianoviaccs/Cake-Miracle#2]
dear kak tati,

sepertinya rancangan flowchart pertama salah, karena konsep masih berupa program penjualan saja, mohon bntuannya untuk mencari referensi dan kita buat ulang flowchart jadi konsep penjualan online,
terima kasih.
tolong cek email yah datanya udh aku send.

**Comment by sapatati** [comment]
OKe saya cek ya via ...
tq

**Comment by vianoviaccs** [comment]
itu baru flowchart login coba di croscheck ulang ya, form menu blm selesai nanti tunggu kabar dari lely ya.. thanks

**Comment by sapatati** [comment]
(https://docs.google.com/presentation/d/1xS2tugZJgO6_9dCesK5B1IITpIlr1TGnyx5LwHUixb4/edit#slide=id.g129dc27356_2_175)

**Comment by sapatati** [comment]
https://docs.google.com/presentation/d/1xS2tugZJgO6_9dCesK5B1IITpIlr1TGnyx5LwHUixb4/edit#slide=id.g129dc27356_2_175

**Comment by vianoviaccs** [comment]
wait im checked..

**Comment by vianoviaccs** [comment]
Dear ka @sapatati 
tolong cek https://drive.google.com/open?id=0B2O03TRJXezbdGdMYU1KaHhHMEE

notes:
1. pada slide blok diagram pemesanan mohon untuk dilakukan perubahan untuk deksripsi projectnya, sesuaikan kata-katanya pada deskripsi pada slide 4&5 yang telah saya ubah.
2. pada slide blog diagram pemilihan pembayaran , mohon untuk dilakukan perubahan atas kata-kata pembeli dan penjual, karena pada sebelumnya digunakan admin dan user, dan untuk untuk user (calon pembeli) bisakah tolong dirubah saja dengan customer, karena user akan digunakan pada kata login untuk hak akses
3. jika dilakukan perubahan pada kata user untuk calon pembeli maka dirubah semua menjadi customer
4. flowchart nya tolong di liat lagi itu simbol untuk proses dan input/output harusnya berbeda, kenapa sama? mohon liat pada email aku sebelumnya, secara alur sudah benar tetapi.
5. pada chart activity diagram untuk cake miracle online, tolong ganti kata2 memajang menjadi mengupload. 

terima kasih, please respond it as soon as possible.

**Comment by sapatati** [comment]
Siap vi... akan saya rubah ...
Thanks yaa

**Comment by vianoviaccs** [comment]
done, next issues untuk revisi, thanks a lot ka @sapatati
