### ISSUE TITLE
Revisi Class diagram

### ISSUE THREAD

**Issue by vianoviaccs** [vianoviaccs/Cake-Miracle#5]
dear @kuratuayuni 

tolong kirimin data visionya ya, kalo gabisa share link send by email aja, 

semoga bisa selsai di minggu ini, supaya kita bisa implementasiin ke coding program.
thanks a lot

**Comment by kuratuayuni** [comment]
class diagram yg mentah kan?
Oke send by email yaa..

**Comment by kuratuayuni** [comment]
class diagram yg mentah kan?
Oke send by email yaa..

**Comment by kuratuayuni** [comment]
Ngomong-ngomong email lw apa ya vii 😆

**Comment by vianoviaccs** [comment]
wkk vianoviaccs@gmail.com

nanti malam gue cek dan coba inheritance di objek utama kita seperti yang kemarin diarahin bapaknya, asli udh abis itu otak gue muter semua cuma blm bisa dtuangin aja udh di kepala bnget ni konsep wkk sabar yaaa,,,

thanks for quick respon :+1:

**Comment by kuratuayuni** [comment]
Bentar ya email gw kebukanya versi gratis nih ngga mantapp..

**Comment by vianoviaccs** [comment]
Disini gbsa share picture ya?
Bisa d drive gak si yun biar share link kesini

**Comment by kuratuayuni** [comment]
Udah gw kirim di email vi,.

**Comment by vianoviaccs** [comment]
done, i'll check it later, thanks a lot @kuratuayuni

**Comment by kuratuayuni** [comment]
be well ,.. 😊

**Comment by vianoviaccs** [comment]
cek wa gue ada picture itu, apa seperti yg kemarin gue bahas di wa yun?

jadinya kue:
kering dan basah
- kode kue
- jenis kue
- harga
- diskon
- komposisi
  ?

**Comment by kuratuayuni** [comment]
Apa penamaan kue kering Dan basah itu Ada artinya maksudnya kaya kering itu cookies atau basah itu brownies?
Iya komposisi atau bahan itu iya tapi kaya gw bilang di WA ya cara pembuatan di hapus aja vi

**Comment by kuratuayuni** [comment]
Gimana menurut kalian tentang basah Dan kering jujur kalo kue nya berupa kue pasar atau jajanan pasar gw ngerti tapi ini beda,tolong dijelasin ya hehee maap masih agak bingung @sapatati @narulitatia

**Comment by narulitatia** [comment]
Kue kering untuk kue yang bertekstur keras tapi renyah yang memiliki kadar air yang sangat rendah biasanya di oven. Tapi kalau kue basah, teksturnya empuk, dan ga tahan lama. Biasanya di kukus . gue juga masih bingung yg di maksud kue basah disini . krna setauu gue kue basah itu yg ada di pasar2. Hehehe @kuratuayuni

**Comment by kuratuayuni** [comment]
tapi bukannya kalo kaya birthday cake atau wedding cake kue nya juga di oven ya? walaupun jenis nya bolu ,.. @narulitatia

**Comment by narulitatia** [comment]
Ruang lingkup cake miracle produknya Kue tart (birthday cake, wedding cake dan), cookies, pudding.

Nah pemilahannya untuk kue basah dan kue kering, kue basah yg ada di cake miracle meliputi semua jenis kue tart dan pudding. Sedangkan kue kering ada cookies ... @kuratuayuni

**Comment by vianoviaccs** [comment]
iya makanya gue jg minta diksh cara pembuatan krn mnrt gue pgaruh, tapi keknya agak ribet kalo dimasukin ke dalam list objek, kue kering cookies kue basah sperti yang @narulitatia itu udh bner penjelasannya, oke thanks a lot team.. :+1: :100: good job!!
