### ISSUE TITLE
Revisi Flowchart dan deskripsi project

### ISSUE THREAD

**Issue by vianoviaccs** [vianoviaccs/Cake-Miracle#6]
Dear ka @sapatati 

tolong di revisi data yang aku kirim kemarin, di share lagi yah link nya , please "PUBLIC" kalau perlu tag ke semua member biar bisa pada paham semua alur project kita.
many thanks :smile:

**Comment by sapatati** [comment]
Oke viaaaa.. sipppp 👌👌

**Comment by sapatati** [comment]
Malam Via...
ini link untuk Revisi, mohon di cek kembali...
thanks

https://docs.google.com/presentation/d/1pq37thcihFgcxz7Gx5-a3ThcVlaQTGOpzFMVHqhaODo/edit#slide=id.g12b0bff6b6_2_108

**Comment by vianoviaccs** [comment]
i'll checked it later, sorry late respon, aku lagi sakit

thanks a lot,,

**Comment by vianoviaccs** [comment]
ka @sapatati ini yg di share di email apa bedanya sama yang di share disini?

plis confirm.

**Comment by sapatati** [comment]
Perbedaanya 👍 
- di flowchart
- acitvity brubah
- kalimat deskripsi di block diagram berubah... 

Atau harus di rubah bagiamana?

**Comment by sapatati** [comment]
@vianoviaccs ...fast respon please  👌👌👌

**Comment by vianoviaccs** [comment]
yg terupdate yg mn?

**Comment by sapatati** [comment]
https://docs.google.com/presentation/d/1pq37thcihFgcxz7Gx5-a3ThcVlaQTGOpzFMVHqhaODo/edit#slide=id.g12b0bff6b6_2_108

Ini link yg setelah revisi ...
Aku merubah sesuai intruksi di issue sebelumnya ...

Maaf kalau msh salah, mohon perubahan sprti apa yg hrus dilakukan)) 😊😊😊

(Perubahan sesuai instruksi dr via)
Trimaksih

**Comment by vianoviaccs** [comment]
thanks a lot for quick respon kaa @sapatati :100:

**Comment by sapatati** [comment]
iya via... perlu aku rubah lagi ga?? *maaf agak ga connect nich

**Comment by vianoviaccs** [comment]
dear ka @sapatati 

tolong revisi lagi yah pada:
1. saat flowchart decision konfirmasi admin itu yes/no tdk ditentukan, coba tlong tentuin kalau aku baca itu kan yes terus admin terima pesanan, then kalau tidak nya tolong diarahkan, apakah ia kembali pada pilihan memilih kue yang diinginkan atau pada melihat produk. menruutku si option pertama
1. buat flow juga untuk metode pembayaran, karena itu dalam deksripsi termasuk kedalam proses,, if u need help pliss asking @narulitatia to help u
2. kalau memang menggunakan bhs inggris tlogn di jadikan inggris semua untuk user, seperti admin, owner dan customer, tadinya kan admin, pemilik dan customer
3. dad untuk pemilik diganti owner sesuaikan bahsanya semua, tapi untuk penjelasan bagan aku rasa b. indo aja biar jelas..

just it, thanks  alot.. im waiting this progress, smoga bisa besok yaah

**Comment by sapatati** [comment]
siapp viaaa

**Comment by sapatati** [comment]
malam Via...
saya kirimkan link REVISI II .. nama dokumen " Cake Miracle Project ( REVISI II )"
perubahan terdapat di :
1. Slide 8 - 9 = 8 flowchart pesanan dan 9 Flowchart metode pembayaran
2. Slide 10 = perubahan Pemilik menjadi Owner ( pada Use Case Owner )
3. Slide 11 = Untuk Header Wishline ( Awalnya Pemilik toko dirubah menjadi Owner )

https://docs.google.com/presentation/d/1nkgE_-BihdfSTB2acjPiqbBNx6aPsfCDrRAdCU1XMoo/edit#slide=id.p4

Mohon bantuannya menjelaskan konsep yang diharapkan agar lebih baik... :)

 Thanks a lot for u intruction ^_^

**Comment by vianoviaccs** [comment]
okey i'll accept it, thanks a lot,, good job team :+1:
