### ISSUE TITLE
list product clasification

### ISSUE THREAD

**Issue by vianoviaccs** [vianoviaccs/Cake-Miracle#7]
dear @narulitatia 

tolong di buatkan list produk berupa tabel referensi dari web cake miracle :cakemiracle.com
jgn lupa di share, link biar data jg ke save di google doc, tolong klasifikasiin dari mulai jenis kue, bahan, cara membuat, pokoknya olah source data dari website itu. semoga minggu ini bisa rilis jadi minggu depan kita bisa gunain.

do as soon as possible :smiley: TFA.

**Comment by narulitatia** [comment]
Sory late respon. Okay vi . nnti klo lagi ga sibuk langsung gue kerjain . klo kata leli, intinya mah Cake Miracle wkwk

**Comment by narulitatia** [comment]
https://docs.google.com/spreadsheets/d/1QhiifeC1PaLRGPywPI9d4QA16zwsArnXRPigRhzhsqQ/edit?usp=sharing

Itu link nya yaak vi. Yg ada ingredientsnya. Mohon di cek. Thanks :)

**Comment by vianoviaccs** [comment]
wait, i'll checked it later.. 

thanks a lot tia @narulitatia

**Comment by narulitatia** [comment]
Okaay vi.

**Comment by vianoviaccs** [comment]
dear @narulitatia 

i think is enough, but belom sesuai yg aku mau, tolong d klasifikasikan jg sebagai kue kering atau basah, karena itu aku masukan gitu jg hahahaha 

thanks a lot, gue mash mkirin inheritance nya udh dpt yg kmrn cm blm di implementasiin

**Comment by narulitatia** [comment]
Oh iya gue lupa jenis kue nya.. Wkwk
Revisi lagikah? Atau next ajah ? Tinggal bedain jenis kue nya .

Nahh yg kemarin ajah vi . agak simple menurut gua mah .

**Comment by vianoviaccs** [comment]
have done!

i'll check it.. thanks a lot , good job :+1:
