### ISSUE TITLE
design concept

### ISSUE THREAD

**Issue by vianoviaccs** [vianoviaccs/Cake-Miracle#8]
dear @lailyfitria 

tolong bantu cari referensi untuk membuat dan ngembangin desain yg sesuai buat project kita.
thanks a lot.. :)
kalau bisa minggu ini sudah ada progressnya ya

**Comment by vianoviaccs** [comment]
@lailyfitria 
lel

cek website ini http://vianovia.esy.es/

progress nya jgn lupa, itu buat referensi yah lel...

**Comment by lailyfitria** [comment]
maaf baru cek,  secepatnya gue cari referensi yang lain yaa..
sorry late respon

**Comment by lailyfitria** [comment]
via tolong cek referensi web ini yaa http://www.ajbakery.com/
kalo menurut gue web ini simple dan paduan warna nya enak dilihat gak bikin sakit mata hehe,coba di cek dulu yaa..makasihh

**Comment by lailyfitria** [comment]
cek yang ini juga yaa http://www.chimelcake.com/

**Comment by vianoviaccs** [comment]
bisa tologn buatin design nya dalam ppt aja kah? sesimple yg lu bisa buat view aja ..
thanks ya yg  http://www.chimelcake.com/ hampir mirip konsep website gue yg td gue kasih lu, kalo yg 
http://www.ajbakery.com/ macam website umumnya..

ini bukan cuma website loh kita buat rancangan sbuah program so gak cuma berfungsi sbg input tp jg bsa ngolah dn output,,

**Comment by lailyfitria** [comment]
tapi untuk desain web yang  http://www.chimelcake.com/ belum terlalu rapih, nanti akan gue buat desain simple nya kalo sudah selesai akan gua info lagi..

**Comment by vianoviaccs** [comment]
hai lel plis read the next duties,

learn the bootstrap, 
i think is enough , im gonna close this issue.
thank u.
